### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by lucasplus** [lonepie/mintty-quake-console#9]
I'm new to github and not quite sure where to put comments, so decided to write it here. This works perfectly for me. Thanks for putting it up! 

There is just one feature that I would love to see. You know that mintty doesn't support tabbed windows. Would you have any interest in adding it to the autohotkey script? You seem to be very good with .ahk. I think it would be great to hit Ctrl+T and get a new window and then be able to cycle through with like Ctrl+Shift+arrow. 

It would require maintaining the pids of the windows. Just not sure how to make that happen. 

Thanks again.

**Comment by ijoseph** [comment]
Details on how you did the hack? I'm almost there, except I can't figure out how to specify different `mintty` instances.

**Comment by lucasplus** [comment]
@ijoseph I don't remember exactly how I did it. I don't use it anymore. From what I remember, let's say you wanted N different windows. I had N different autohotkey scripts (.ahk) and no .ini files. [Here](https://github.com/lonepie/mintty-quake-console/blob/master/mintty-quake-console.ahk#L28) starts the code dealing with the deafaults. I changed [this line](https://github.com/lonepie/mintty-quake-console/blob/master/mintty-quake-console.ahk#L30) in every .ahk file to be [Windows Key + 1], [Windows Key + 2], ..., [Windows Key +N]. I forgot how to specify windows key. You'll have to look it up in the autohotkey docs. I then turned each of the differently named .ahk files into .exe files. I believe you right click on the .ahk file to do that. I then put all of those .ahk files in the startup folder. I think I remember sometimes having issues where only the same mintty window came down. I think I would kill that mintyy instance with alt+f4 and then hit it again and it would work.

**Comment by ijoseph** [comment]
Ah, turning them into `.exe`'s might be the trick; I had done everything except that. Thanks! What do you use now, if I may ask?

**Comment by lucasplus** [comment]
Cool. No problem. I don't use mintty for anything anymore. I used to like it for things like moving and exploring directories. Also, vim. I guess I just got used to doing it the windows way and using Atom for text editing.

**Comment by ijoseph** [comment]
Epilogue: I never did get that working, but I realized that `tmux `has tab functionality built-in, and that I'd been meaning to start using that anyhow. 

Thanks for the help above!

**Comment by lucasplus** [comment]
Sure. No problem.
